# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build push an image
      inputs:
        containerRegistry: 'AGeStore'
        repository: 'AGeStoreApp'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/images/ubuntu/Dockerfile'
        tags: |
          $(tag)
          latest

##### Deploy Stage #####
- stage: Deploy
  displayName: Deploy to AKS
  jobs:
    - job: deploy
      displayName: Deploy
      steps:
      - task: KubernetesManifest@1
        inputs:
          action: 'createSecret'
          connectionType: 'kubernetesServiceConnection'
          kubernetesServiceConnection: 'AGeStore_Kuber'
          namespace: 'default'
          secretType: 'dockerRegistry'
          secretName: 'AGeStore-auth'
          dockerRegistryEndpoint: 'AGeStore'
    
      # AKS에 배포
      - task: KubernetesManifest@1
        inputs:
          action: 'deploy'
          connectionType: 'kubernetesServiceConnection'
          kubernetesServiceConnection: 'AGeStore_Kuber'
          namespace: 'default'
          manifests: 
            $(Build.SourcesDirectory)/manifests/deployment.yml
            $(Build.SourcesDirectory)/manifests/service.yml
