version: '2'
services:
    gomzion:
        image: ghcr.io/gomzion/ag_estore:0.2
        container_name: nginx_php81_mssql
        stdin_open: true
        tty: true
        volumes:
            - ./source:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
        environment:
            - TZ=Asia/Seoul
        networks:
            - mynetwork
networks:
    mynetwork:
        driver: bridge
        name: mynetwork
        external: true