apiVersion: v1
kind: Service
metadata:
  name: agestore
  annotations:
  # AAG의 Backendpool에 등록하는 IP가 됩니다. AKS 노드가 사용하는 Azure Subnet 대역으로 지정
  # 만약 아이피가 중복되어 있다면 다른 아이피로 변경해야 합니다.
    service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.2.2.5
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      port: 80
    - name: https-port
      port: 443
  selector:
    app: agestoreapp # Pod의 Label과 일치시켜야 합니다.